#server:
  #port: 8443
  #ssl:
  #key-store: classpath:keystore.p12
  # key-store-password: 123456
  # key-store-type: PKCS12
  # key-alias: tomcat
spring:
  session:
    store-type: none
  datasource:
    data: test
    url: jdbc:postgresql://localhost:6432/spring-cloude2
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: true
    suffix: .html
  redis:  
    database:  0  
    host:  127.0.0.1  
    port:  6379  
    password: 123456  
    pool:  
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
      timeout: 0  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.winter.model
  type-handlers-package: com.user.utils

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  file: ../logs/log.log
  level:
    net:
      chinacloud:
        smartwater:
          mapper: DEBUG
project:
  timeInterceptor: true
debug: true
    