server:
  port: 8080
spring:
  session:
    store-type: none
  datasource:
    data: test
    url: jdbc:mysql://localhost:3306/springmvc
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: localhost
    port: 6379 
    database: 0
    password: 
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    timeout: 30000
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.winter.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    net:
      chinacloud:
        smartwater:
          mapper: DEBUG
    
  
  
    